import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = { createdAt: integer("created_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()), updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().$defaultFn(() => new Date()) };
export const organizations = sqliteTable("organizations", { id: text("id").primaryKey(), type: text("type", { enum: ["school", "classroom", "family"] }).notNull(), name: text("name").notNull(), settingsJson: text("settings_json", { mode: "json" }).notNull().default("{}"), ...timestamps });
export const users = sqliteTable("users", { id: text("id").primaryKey(), organizationId: text("organization_id").references(() => organizations.id), role: text("role", { enum: ["student", "teacher", "parent", "admin"] }).notNull(), displayName: text("display_name").notNull(), email: text("email"), settingsJson: text("settings_json", { mode: "json" }).notNull().default("{}"), deletedAt: integer("deleted_at", { mode: "timestamp" }), ...timestamps }, (table) => [index("idx_users_organization_id").on(table.organizationId), uniqueIndex("idx_users_organization_email").on(table.organizationId, table.email)]);
export const studentGuardianLinks = sqliteTable("student_guardian_links", { id: text("id").primaryKey(), studentId: text("student_id").notNull().references(() => users.id), guardianId: text("guardian_id").notNull().references(() => users.id), status: text("status", { enum: ["pending", "active", "revoked"] }).notNull().default("pending"), consentRecordedAt: integer("consent_recorded_at", { mode: "timestamp" }), ...timestamps }, (table) => [uniqueIndex("idx_student_guardian_pair").on(table.studentId, table.guardianId), index("idx_guardian_links_guardian").on(table.guardianId, table.status)]);
export const books = sqliteTable("books", { id: text("id").primaryKey(), isbn10: text("isbn10"), isbn13: text("isbn13"), openLibraryId: text("open_library_id"), googleBooksId: text("google_books_id"), title: text("title").notNull(), authorsJson: text("authors_json", { mode: "json" }).notNull(), coverUrl: text("cover_url"), publicationYear: integer("publication_year"), pageCount: integer("page_count"), metadataJson: text("metadata_json", { mode: "json" }).notNull().default("{}"), ...timestamps }, (table) => [uniqueIndex("idx_books_isbn13").on(table.isbn13), index("idx_books_open_library_id").on(table.openLibraryId)]);
export const quizSources = sqliteTable("quiz_sources", { id: text("id").primaryKey(), bookId: text("book_id").notNull().references(() => books.id), organizationId: text("organization_id").notNull().references(() => organizations.id), sourceType: text("source_type", { enum: ["public_domain", "teacher_notes", "authorized_guide", "open_reference", "approved_quiz"] }).notNull(), contentHash: text("content_hash").notNull(), sufficiencyStatus: text("sufficiency_status", { enum: ["pending", "sufficient", "insufficient"] }).notNull().default("pending"), createdBy: text("created_by").notNull().references(() => users.id), ...timestamps }, (table) => [index("idx_quiz_sources_book_org").on(table.bookId, table.organizationId)]);
export const quizzes = sqliteTable("quizzes", { id: text("id").primaryKey(), bookId: text("book_id").notNull().references(() => books.id), sourceId: text("source_id").notNull().references(() => quizSources.id), organizationId: text("organization_id").notNull().references(() => organizations.id), version: integer("version").notNull(), status: text("status", { enum: ["draft", "review_required", "approved", "archived"] }).notNull().default("draft"), gradeBand: text("grade_band", { enum: ["1-2", "3-5", "6-8"] }).notNull(), model: text("model"), promptVersion: text("prompt_version"), approvedBy: text("approved_by").references(() => users.id), approvedAt: integer("approved_at", { mode: "timestamp" }), ...timestamps }, (table) => [uniqueIndex("idx_quizzes_org_book_version").on(table.organizationId, table.bookId, table.version), index("idx_quizzes_org_status").on(table.organizationId, table.status)]);
export const questions = sqliteTable("questions", { id: text("id").primaryKey(), quizId: text("quiz_id").notNull().references(() => quizzes.id), position: integer("position").notNull(), prompt: text("prompt").notNull(), choicesJson: text("choices_json", { mode: "json" }).notNull(), correctIndex: integer("correct_index").notNull(), skill: text("skill").notNull(), rationale: text("rationale").notNull(), sourceReference: text("source_reference").notNull(), confidence: real("confidence").notNull(), visualJson: text("visual_json", { mode: "json" }), ...timestamps }, (table) => [uniqueIndex("idx_questions_quiz_position").on(table.quizId, table.position)]);
export const assignments = sqliteTable("assignments", { id: text("id").primaryKey(), quizId: text("quiz_id").notNull().references(() => quizzes.id), assignedBy: text("assigned_by").notNull().references(() => users.id), studentId: text("student_id").references(() => users.id), classId: text("class_id").references(() => organizations.id), availableAt: integer("available_at", { mode: "timestamp" }).notNull(), dueAt: integer("due_at", { mode: "timestamp" }), attemptLimit: integer("attempt_limit").notNull().default(1), passingScore: integer("passing_score").notNull().default(70), reviewMode: text("review_mode", { enum: ["score_only", "missed_only", "guided", "full"] }).notNull().default("score_only"), ...timestamps }, (table) => [index("idx_assignments_student_available").on(table.studentId, table.availableAt), index("idx_assignments_class_available").on(table.classId, table.availableAt)]);
export const attempts = sqliteTable("attempts", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), quizId: text("quiz_id").notNull().references(() => quizzes.id), quizVersion: integer("quiz_version").notNull(), answersJson: text("answers_json", { mode: "json" }).notNull(), scorePercent: integer("score_percent").notNull(), pointsEarned: real("points_earned").notNull(), startedAt: integer("started_at", { mode: "timestamp" }).notNull(), submittedAt: integer("submitted_at", { mode: "timestamp" }), ...timestamps }, (table) => [index("idx_attempts_user_submitted").on(table.userId, table.submittedAt), index("idx_attempts_quiz_id").on(table.quizId)]);
export const goals = sqliteTable("goals", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), periodType: text("period_type", { enum: ["week", "month", "term"] }).notNull(), startsAt: integer("starts_at", { mode: "timestamp" }).notNull(), endsAt: integer("ends_at", { mode: "timestamp" }).notNull(), targetPoints: real("target_points").notNull(), ...timestamps }, (table) => [index("idx_goals_user_period").on(table.userId, table.startsAt, table.endsAt)]);
export const rewards = sqliteTable("rewards", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id), rewardType: text("reward_type").notNull(), rewardKey: text("reward_key").notNull(), earnedAt: integer("earned_at", { mode: "timestamp" }).notNull(), ...timestamps }, (table) => [uniqueIndex("idx_rewards_user_key").on(table.userId, table.rewardKey)]);
